### ISSUE TITLE
Fjerne (eller gjennomføre) TODO i arkivmelding.xsd

### ISSUE THREAD

**Issue by steinarhenriksen** [ks-no/fiks-arkiv-specification#103]
Kan være greit å fjerne (eller gjennomføre) TODO i arkivmelding.xsd

https://github.com/ks-no/fiks-arkiv-specification/blob/main/Schema/V1/no.ks.fiks.arkiv.v1.arkivering.arkivmelding.xsd#L12

**Comment by jarleborsheim** [comment]
Jepp. Done
