### ISSUE TITLE
Gjere journalpost.avskrivningsdato frivillig i arkivmelding.xsd

### ISSUE THREAD

**Issue by steinarhenriksen** [ks-no/fiks-arkiv-specification#104]
Er det aktuelt å gjere journalpost.avskrivningsdato frivillig?

Det kan hende at eFormidlings usecase avviker fra resten. Me ønskjer at det aller meste av metadata er frivillig, med mindre det er strengt nødvendig å inkludere informasjonen.

https://github.com/ks-no/fiks-arkiv-specification/blob/main/Schema/V1/no.ks.fiks.arkiv.v1.arkivering.arkivmelding.xsd#L174

**Comment by sturtzel** [comment]
Dette er en oversett bug. Avskrivning er etter offentleglova, men først når en inngående journalpost er håndtert. Det er ikke krav for notater og ikke i bruk for utgående eller saksfremlegg.

**Comment by jarleborsheim** [comment]
Merget og fikset og kan stenges
