### ISSUE TITLE
Gjere dokumentbeskrivelse.dokumenttype frivillig i arkivmelding.xsd

### ISSUE THREAD

**Issue by steinarhenriksen** [ks-no/fiks-arkiv-specification#105]
Er det aktuelt å gjere dokumentbeskrivelse.dokumenttype frivillig?

Det kan hende at eFormidlings usecase avviker fra resten. Me ønskjer at det aller meste av metadata er frivillig, med mindre det er strengt nødvendig å inkludere informasjonen.

https://github.com/ks-no/fiks-arkiv-specification/blob/main/Schema/V1/no.ks.fiks.arkiv.v1.arkivering.arkivmelding.xsd#L201

Arkivverkets NOARK-metadata beskriver verdien slik

```
Ingen obligatoriske typer. Aktuelle verdier kan f.eks. være:
- Brev
- Rundskriv
- Faktura
- Ordrebekreftelser
```

**Comment by jarleborsheim** [comment]
Done. Stenger denne saken
