### ISSUE TITLE
Gjere dokumentobjekt.versjonsnummer frivillig i arkivmelding.xsd

### ISSUE THREAD

**Issue by steinarhenriksen** [ks-no/fiks-arkiv-specification#106]
Er det aktuelt å gjere dokumentobjekt.versjonsnummer frivillig?

Det kan hende at eFormidlings usecase avviker fra resten. Me ønskjer at det aller meste av metadata er frivillig, med mindre det er strengt nødvendig å inkludere informasjonen.

https://github.com/ks-no/fiks-arkiv-specification/blob/main/Schema/V1/no.ks.fiks.arkiv.v1.arkivering.arkivmelding.xsd#L226

**Comment by sturtzel** [comment]
Vi kan si at standardverdien er 1. Normalt overføres kun ett dokumentobjekt for en dokumentbeskrivelse. Da kan denne være frivillig.

Overføres det flere må det angis versjonsnummer og variantformat.

Ref. også 107.
