### ISSUE TITLE
Gjere dokumentobjekt.variantformat frivillig i arkivmelding.xsd

### ISSUE THREAD

**Issue by steinarhenriksen** [ks-no/fiks-arkiv-specification#107]
Er det aktuelt å gjere dokumentobjekt.variantformat frivillig?

Det kan hende at eFormidlings usecase avviker fra resten. Me ønskjer at det aller meste av metadata er frivillig, med mindre det er strengt nødvendig å inkludere informasjonen.

https://github.com/ks-no/fiks-arkiv-specification/blob/main/Schema/V1/no.ks.fiks.arkiv.v1.arkivering.arkivmelding.xsd#L227

**Comment by sturtzel** [comment]
Vi kan si at standardverdi er produksjonsformat. De fleste arkivkjerner vil nok uansett ikke stole helt på fagsystemet her, ta imot som produksjonsformat og så validere før det blir arkivformat.

Men hvis man har med flere dokumentobjekter må det angis variantformat for at arkivkjernen skal kunne skille på dem.
