### ISSUE TITLE
Gjere dokumentobjekt.format frivillig i arkivmelding.xsd

### ISSUE THREAD

**Issue by steinarhenriksen** [ks-no/fiks-arkiv-specification#108]
Er det aktuelt å gjere dokumentobjekt.format frivillig?

Det kan hende at eFormidlings usecase avviker fra resten. Me ønskjer at det aller meste av metadata er frivillig, med mindre det er strengt nødvendig å inkludere informasjonen.

https://github.com/ks-no/fiks-arkiv-specification/blob/main/Schema/V1/no.ks.fiks.arkiv.v1.arkivering.arkivmelding.xsd#L228

**Comment by sturtzel** [comment]
Så lenge vi har filnavn og filnavn inneholder filtype er den strengt tatt ikke nødvendig.

Arkade 5 validerer den nå mot filtype + sjekker filinnhold vs. tabell over filtyper, ref. https://www.nationalarchives.gov.uk/PRONOM/

Fagsystemer vil nok alltid sette denne lik filtypen, så ja, antagelig overflødig i tjenestene for alle andre enn Arkivverket.
