### ISSUE TITLE
Gjere korrespondansepart.erBehandlingsansvarlig frivillig i arkivmelding.xsd

### ISSUE THREAD

**Issue by steinarhenriksen** [ks-no/fiks-arkiv-specification#109]
Er det aktuelt å gjere korrespondansepart.erBehandlingsansvarlig frivillig?

Det kan hende at eFormidlings usecase avviker fra resten. Me ønskjer at det aller meste av metadata er frivillig, med mindre det er strengt nødvendig å inkludere informasjonen.

https://github.com/ks-no/fiks-arkiv-specification/blob/main/Schema/V1/no.ks.fiks.arkiv.v1.arkivering.arkivmelding.xsd#L267

**Comment by jarleborsheim** [comment]
Vi tar denne opp på neste møte

**Comment by jarleborsheim** [comment]
Legger det til som kommentar at den skal være default=false i xsd

**Comment by jarleborsheim** [comment]
Stenger. Løst i PR
