### ISSUE TITLE
Fjerne dokumentobjekt.filnavn fra arkivmelding.xsd

### ISSUE THREAD

**Issue by steinarhenriksen** [ks-no/fiks-arkiv-specification#110]
Er det aktuelt å fjerne dokumentobjekt.filnavn?

Det virker som ein duplikat av dokumentobjekt.referanseDokumentFil ?

https://github.com/ks-no/fiks-arkiv-specification/blob/main/Schema/V1/no.ks.fiks.arkiv.v1.arkivering.arkivmelding.xsd#L233

**Comment by sturtzel** [comment]
De er ikke helt det samme.

Filnavn: Det opprinnelige filnavnet som gjerne skal brukes hvis filen lastes ned. Kan inneholde alle lovlige tegn for filnavn. Egnet også for visning.
ReferanseDokumentFil: URL som kan brukes for å hente filen. Vil normalt ikke inneholde tegn som komma, æøå etc.

**Comment by sturtzel** [comment]
Tenkt litt mer. ReferanseDokumentFil er kun aktuell der dokumentet faktisk er tilgjengelig via URL-en. I mange tilfeller vil det ikke stemme, f.eks. alt som er unntatt offentlighet og for eInnsyn der dokumentene ikke er lagt ut offentlig.

Den bør derfor være minOccurs 0.

Jeg er litt mer skeptisk til ikke å ha angivelse av filnavn som infoelement.

**Comment by jarleborsheim** [comment]
Laget et forslag som vi kan diskutere på neste møte ☝️
