### ISSUE TITLE
Oppdatering av dokumentbeskrivelse

### ISSUE THREAD

**Issue by sturtzel** [ks-no/fiks-arkiv-specification#127]
For mappe og for registrering er det maxOccurs unbounded, mens det er 0-1 for dokumentbeskrivelse.

Det er vel ikke bevisst?

https://github.com/ks-no/fiks-arkiv-specification/blob/main/Schema/V1/meldingstyper/meldingstyper.json angir at kvitteringen skal være no.ks.fiks.arkiv.v1.arkivering.arkivmelding.oppdater.kvittering. Den kvitteringen er vel ikke spesifisert, kun for opprett.

**Comment by sturtzel** [comment]
Meldingstypen er referert som svar i json-filen, men det finnes ingen xsd. Det bør være en kvittering på en oppdateringsfunksjon, men det er ikke sikkert at den trenger å være mer enn "OK".

**Comment by jarleborsheim** [comment]
Oppdatere dokumentasjon og meldingstyper.json

**Comment by jarleborsheim** [comment]
Fikset dokumentasjon og meldingstyper.json. Avslutter denne oppgaven
