### ISSUE TITLE
Gjere ein del av felta i journalpostKvittering frivillige

### ISSUE THREAD

**Issue by steinarhenriksen** [ks-no/fiks-arkiv-specification#137]
Er det aktuelt å gjere ein del av felta i journalpostKvittering frivillige?

- journalaar
- journalsekvensnummer
- journalpostnummer
- journalposttype
- journalstatus
- journaldato

https://github.com/ks-no/fiks-arkiv-specification/blob/main/Schema/V1/no.ks.fiks.arkiv.v1.arkivering.arkivmelding.opprett.kvittering.xsd#L68

**Comment by sturtzel** [comment]
Slike mottakssentraler kan også velge ikke å journalføre.

Hvis det skal gjøres en manuell operasjon før journalføringen er komplett skal antagelig kvitteringsmeldingen returneres etter at det trinnet er ferdig.

Antagelig risikerer man at avsender blir utålmodig og sender på nytt...

**Comment by jarleborsheim** [comment]
Vi stenger denne da arkivering-mottatt-kvittering flyten gjør at det skal være slik
