### ISSUE TITLE
virksomhetsspesifikkeMetadata

### ISSUE THREAD

**Issue by jarleborsheim** [ks-no/fiks-arkiv-specification#159]
Kan vi egentlig beholde virksomhetsspesifikkeMetadata som xs:anyType? På f.eks. mappe i arkivmelding.
Det virker for åpent og man får generert det til typen Object i C#.

**Comment by sturtzel** [comment]
Noark spesifiserer denne som XML:

6.4.8 Virksomhetsspesifikke metadata
Dersom Noark 5-løsningen inneholder metadataelementer som ikke er spesifisert i Noark 5, er det likevel mulig å ta disse med i arkivuttrekket. Slike virksomhetsspesifikke metadata blir en del av arkivstrukturen og tas derfor med i arkivstruktur.xml. De virksomhetsspesifikke metadataene kan knyttes til arkivenhetene mappe, registrering eller sakspart gjennom det overordnede elementet virksomhetsspesifikkeMetadata som er av XML Schema-datatypen anyType.

At det blir et generelt objekt er OK. Dataene burde kunne vært JSON i tillegg til XML (Noark 5 er 15 år gammel).

**Comment by jarleborsheim** [comment]
Ok. Da foreslår jeg å dokumentere feltet `virksomhetsspesifikkeMetadata` i f.eks. oppdatering for en part på denne måten:

```
### `virksomhetsspesifikkeMetadata`
#### Definisjon
Oppdatering av `virksomhetsspesifikkeMetadata` for parten. 
Dersom Noark 5-løsningen inneholder metadataelementer som ikke er spesifisert i Noark 5,
er det likevel mulig å ta disse med i arkivuttrekket. 
Slike virksomhetsspesifikke metadata blir en del av arkivstrukturen. 
De virksomhetsspesifikke metadataene kan knyttes til arkivenhetene mappe, registrering eller sakspart gjennom det overordnede elementet virksomhetsspesifikkeMetadata som er av XML Schema-datatypen anyType og blir et generelt objekt.
Dataene kan dermed være f.eks. JSON i tillegg til XML for dette feltet.

```

**Comment by sturtzel** [comment]
Jeg foreslår at "Dersom" etc. erstattes med følgende:
Virksomhetsspesifikke metadata (VSM) benyttes for å arkivere data som det ikke er Noark-felt for. Det anbefales å legge fagspesifikke data i felt for VSM, f.eks. data som spesifiserer saksbehandlingen eller søknadsdata som ikke arkiveres som dokumenter. VSM skal være strukturerte data slik at de kan benyttes senere, fortrinnsvis i XML.
