### ISSUE TITLE
Hvordan vite hvilken kvittering som gjelder hvilken dokumentbeskrivelse i opprett registrering

### ISSUE THREAD

**Issue by sturtzel** [ks-no/fiks-arkiv-specification#165]
I kvitteringsmeldingen returneres systemID, men det holder ikke med mindre man er garantert at kvitteringen kommer i samme rekkefølge som input.

Jeg foreslår at dokumentnummer tas med i kvitteringen.

Hvis man kan garantere at systemID inn ved opprett objekt blir tatt som systemID i arkivet, er det ikke så prekært med dokumentnummer.

**Comment by jarleborsheim** [comment]
Stenger den da det er løst
