### ISSUE TITLE
Mappe.klassifikasjon inneholder for lite data

### ISSUE THREAD

**Issue by sturtzel** [ks-no/fiks-arkiv-specification#167]
Objektet klassifikasjon inneholder kun referanser til klassifikasjonssystem og klasse. Det forutsetter at disse eksisterer fra før og at fagsystemet kjenner dem.

Ved seriearkiv / objektordnet klassifikasjon vil det lages nye klasser automatisk, f.eks. ved byggesak på en ny eiendom.
Om en klasse skal være skjermet på et objekt kan være relatert til selve objektet.

Siden det ikke finnes egne tjenester for å registrere klasse bør objektet klassifikasjon erstattes av objektet klasse og klassifikasjonsid bør inngå i klasse, ref. GeoIntegrasjon. Evt. kan klassifikasjon gjøres om til å inkludere klasse for å unngå felt som rekkefølge i klasseobjektet.

**Comment by jarleborsheim** [comment]
`Klassifikasjon` kan inneholde de viktigste feltene fra `klasse`.  Klasse kan da evt også tas bort fra arkivmelding-opprett.

**Comment by jarleborsheim** [comment]
Vi må også endre i arkivmelding.oppdatering. Slik den er nå:
```
    <xs:complexType name="klassifikasjonOppdatering">
        <xs:sequence>
            <xs:element name="klassifikasjonssystemID" type="n5mdk:klassifikasjonssystemID"/>
            <xs:element name="klasseID" type="n5mdk:klasseID" minOccurs="0"/>
            <xs:element name="tittel" type="n5mdk:tittel" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
```
Vi må ha   disse 2 som identifikatorerer sammen som en ny complextype (tilsvarende som gjort andre steder på oppdatering): 

```
<xs:element name="klassifikasjonssystemID" type="n5mdk:klassifikasjonssystemID"/>
<xs:element name="klasseID" type="n5mdk:klasseID"/>
```

Samtidig som man får lov til å oppdatere de.
Pluss legge til at man får lov til å endre "erSkjermet".

**Comment by jarleborsheim** [comment]
Stenger da denne er løst
