### ISSUE TITLE
Felt som kan oppdateres i arkivmelding.oppdater

### ISSUE THREAD

**Issue by sturtzel** [ks-no/fiks-arkiv-specification#175]
Det er en rekke felt i arkivmeldingen som ikke er med i felt som kan oppdateres. Noen felt er det naturlig at ikke kan endres som ID-felt mens andre antagelig kun har blitt uteglemt. Av erfaring vet jeg at det fort kommer en applikasjon med behov for å endre et felt som ikke kan endres via tjenesten. Fredrikstad kommune har nylig etterlyst muligheten for å sette datoer via GI. Det var da jeg så at Fiks Arkiv heller ikke gir de mulighetene. Jeg foreslår at følgende felt legges til i arkivmelding.oppdater:

Mappe:
noekkelord (ved endring: Ny liste)
oppbevaringssted (ved endring: Ny liste) (trengs feltet?)
opprettetDato
opprettetAv
avsluttetDato
avsluttetAv
arkivdel
referanseEksternNoekkel
mappetype

Saksmappe:
saksdato
utlaantDato (eller utgå fra arkivmelding)
utlaantTil (eller utgå fra arkivmelding)
presedens (registreres alltid i etterkant)
adresse (eller utgå fra arkivmelding)

Registrering:
opprettetDato
opprettetAv
arkivertDato
arkivertAv
referanseForelderMappe (kan bli aktuelt for Eiendomssak hvis krav om splitting i saker pr. eiendom opprettholdes)
noekkelord (ved endring: Ny liste)
forfatter
oppbevaringssted (ved endring: Ny liste) (trengs feltet?)

Journalpost:
journalposttype?
journalstatus
journaldato
dokumentetsDato
mottattDato
sendtDato
forfallsdato
offentlighetsvurdertDato
utlaantDato (eller utgå fra arkivmelding)
utlaantTil (eller utgå fra arkivmelding)
journalenhet
dokumentflyt (ved endring: Ny liste?)
presedens
avskrivningsdato? (egne tjenester, men de setter kun implisitt dette feltet)

Dokumentbeskrivelse:
dokumentstatus
forfatter
opprettetDato
opprettetAv
oppbevaringssted
tilknyttetRegistreringSom?
dokumentnummer?
tilknyttetDato?
tilknyttetAv?
part

Samtidig bør rekkefølgen på felt i objektene endres slik at det blir likt som i arkivmelding.opprett.

**Comment by jarleborsheim** [comment]
Trenger ikke oppdatere utlaan-felter da de tas bort

**Comment by jarleborsheim** [comment]
Må dokumenteres at felter som er nye lister som kommer inn er faktisk nye. Dokumenteres i skjema og i wiki

**Comment by jarleborsheim** [comment]
Merget og kan stenges
