### ISSUE TITLE
Ønske om å kunne sende inn saksmappe med journalpost i en melding

### ISSUE THREAD

**Issue by jarleborsheim** [ks-no/fiks-arkiv-specification#187]
Man ønsker å kunne sende inn en arkivmelding opprett melding, som inneholder en saksmappe med journalpost(er) som skal opprettes. Hvis saksmappe finnes fra før opprettes bare journalposten(e), mens hvis saksmappe ikke finnes opprettes saksmappe pluss jornalpost(er).

Utfordringen ligger i at man kan få delvis opprettet alt. Kvittering man får tilbake må i så fall gi informasjon om hva som gikk ok og hva som gikk galt.

**Comment by sturtzel** [comment]
Dette bør være en egen tjeneste som bør være lik dagens opprett med tre endringer: Ikke choice, maxOccurs = 1 på mappe og maxOccurs = unbounded på journalpost.
Kvitteringsmeldingen blir en liste over kvitteringer pr. hovedobjekt der kvitteringene kan være både kvittering og feilmelding.
Rekken avbrytes ved første feil.

**Comment by jarleborsheim** [comment]
Det må bli en ny meldingstype for å opprette saksmappe med 1 journalpost. 
Det samme gjelder da kvittering som vil inneholde hva som gikk ok og hva som feilet.
Kvitteringen vil returnere informasjon om hva som ble opprettet, tilsvarende slik som kvittering for arkivmelding opprett. I tillegg vil den ha liste med feilmeldinger for det som feilet med id på det som ble forsøkt opprettet. 

- Det skal ikke gjøres noen oppdatering på en eksisterende saksmappe hvis man får inn f.eks. tittel som ikke stemmer overens.
- Identifikatorer på mappe er eksternNoekkel.  
- Man må alltid sørge for å ha med alle metadata for å kunne opprette mappen på en god måte. Den vil opprettes hvis den ikke eksisterer.

**Comment by jarleborsheim** [comment]
Det jeg lurte på å gjøre, var å lage det slik at man returnerer en choice mellom eksisterendeMappeKvittering eller nyMappeKvittering. Innhold er foreløpig likt men forskjell på complexType. Hvis det er noe som bare skal returneres i kvittering når man oppretter en ny så kan det fordeles ut der det er fornuftig. Jeg kommer med forslag straks.
