### ISSUE TITLE
Legge til språk som parameter i søk og hent-meldinger

### ISSUE THREAD

**Issue by jarleborsheim** [ks-no/fiks-arkiv-specification#188]
Vi ser at det kan være nødvendig å definere hvilket språk man ønsker å få i retur. 
I søk og hent-meldinger.
Bør være en kode og følge en standard på definsjon av språk. ISO-639?

**Comment by sturtzel** [comment]
Fra GeoIntegrasjon:
`	<xs:complexType name="Kontekst">
		<xs:sequence>
			<xs:element name="spraak" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="klientnavn" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="klientversjon" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="systemversjon" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
`

https://no.wikipedia.org/wiki/Liste_over_ISO_639-1-koder
Grei oversikt.

**Comment by jarleborsheim** [comment]
Ikke en kodeliste men at vi viser til iso 639-1 kodene. 
Hvis mottakende system ikke støtter språket defaultes det til konfigurert default språk.
Legges til i søk og hent-meldinger.
