### ISSUE TITLE
La klassifikasjonssystem i arkivmelding.opprett kunne settes av tjener via regel eller annen konfigurasjon

### ISSUE THREAD

**Issue by sturtzel** [ks-no/fiks-arkiv-specification#189]
Feltet klassifikasjonssystemID i objektet klassifikasjon bør endres til minOccurs 0.

Dette feltet kan settes på tjenersiden for primær klassifikasjon da det er gitt av oppsettet av arkivdelene. Verdien varierer fra arkiv til arkiv. Spesielt for seriearkiv er det greit å kunne sette kun klasseID (og beskrivelse).

**Comment by jarleborsheim** [comment]
Dette gjelder kun i arkivmelding opprett antar jeg da. I arkivstruktur skal den forbli minOccurs 1?

**Comment by sturtzel** [comment]
> Dette gjelder kun i arkivmelding opprett antar jeg da. I arkivstruktur skal den forbli minOccurs 1?

Ja
