### ISSUE TITLE
Behov for å detektere endringer

### ISSUE THREAD

**Issue by sturtzel** [ks-no/fiks-arkiv-specification#218]
Ref. https://github.com/ks-no/fiks-arkiv-specification/wiki/Brukstilfelle-Endring-fra-arkiv-tilbake-til-fagsystem

For å kunne detektere endringer i arkivet er det behov for et søkbart felt for "sist endret". Dette feltet kan også benyttes for å alarmere saksbehandler hvis vedkommende ønsker å gjøre oppdateringer i fagsystemet, endringer som potensielt vil overstyre endringer arkivet har gjort.

For å detektere nye journalposter i en sak holder det å søke på registrert dato (som finnes). Det scenariet er mer aktuelt da respons fra en part i saken (eller andre) kan ha blitt registrert av arkivpersonale rett i arkivet som ny journalpost.

**Comment by jarleborsheim** [comment]
Could be that this should be patched for those usecases that need to search for changes made by other systems?
If it is important for those usecases.

**Comment by sturtzel** [comment]
I see that this need would result in an extra enum in mappeSokefelt and in registreringSokefelt.

I suggest that we include these changes, but that we in V1 limits the changes to enum changes in innsyn.sok.xsd. Changes to arkivmelding may be taken in a V2 version.

**Comment by jarleborsheim** [comment]
Hei @sturtzel .

Jeg ble litt usikker på om vi egentlig trenger disse 2 nye feltene i enum for `"mappeSokefelt"` og `"registreringSokefelt"`?
Hvis målet er å kunne gjøre et søk for å se om det noen endringer, kan man ikke bruke de eksisterende enum verdiene "mappeEndretDato" og "registreringEndretDato" og finne ut om det finnes noen nye registreringer/mapper som har kommet etter den datoen man selv har? Altså at man spør om type "mappeEndretDato" > sist lokale endret dato. Hvis det kommer noe tilbake så har det kommet noe nytt?

**Comment by sturtzel** [comment]
Jepp. De ligger allerede inne som søkefelt, ser jeg. Da har vi det vi trenger i V1.

**Comment by jarleborsheim** [comment]
Closing this issue. We can use the existing enum values for `mappeEndretDato` and `registreringEndretDato`
