### ISSUE TITLE
Part, fields present in opprett, but missing in arkivstruktur

### ISSUE THREAD

**Issue by sturtzel** [ks-no/fiks-arkiv-specification#223]
The following fields are missing:
organisasjonID
personID
erSkjermet
erPersonnavn

**Comment by jarleborsheim** [comment]
When I look a little bit more closely at differences between `arkivstruktur.xsd` and `no.ks.fiks.arkiv.v1.arkivering.arkivmelding.opprett.xsd` I wonder if perhaps we have som more fields missing in `arkivstruktur.xsd` or that we could delete?

I create a pull-request with your requested changes, and then I would like to take som time going through these differences in our next meeting. Just to make sure.

**Comment by sturtzel** [comment]
Output must reflect input, so I agree with the additional changes as well
