### ISSUE TITLE
Kassasjon - tas bort? 

### ISSUE THREAD

**Issue by jarleborsheim** [ks-no/fiks-arkiv-specification#228]
Jeg ser at vi har complexType definert for "kassasjon" i arkivmelding opprett. Men brukes ikke noen steder.
Jeg mener dette må være at vi har glemt å ta bort definisjonen av objektet i skjemaet etter vi tok det bort som referanse andre steder. 
Skal vi rydde det bort nå helt?
```
    <xs:complexType name="kassasjon">
        <xs:sequence>
            <xs:element name="kassasjonsvedtak" type="n5mdk:kassasjonsvedtak"/>
            <xs:element name="kassasjonshjemmel" type="n5mdk:kassasjonshjemmel" minOccurs="0"/>
            <xs:element name="bevaringstid" type="n5mdk:bevaringstid"/>
            <xs:element name="kassasjonsdato" type="n5mdk:kassasjonsdato"/>
        </xs:sequence>
    </xs:complexType>
```

Jeg ser forøvrig at objektet finnes fremdeles i arkivstruktur.xsd samt er i bruk der under flere objekter (f.eks. registrering. Altså er det med i hent-meldinger.

**Comment by sturtzel** [comment]
Arkivverket krever at kassasjon er utført før avlevering. Informasjonen bør derfor ikke fjernes fra arkivmelding. Men det er greit at vi ikke har det med i opprett og oppdater. Jeg mener vi sa at kassasjon kunne håndteres av arkivet. Det bør dokumenteres. Da kan du fjerne det fra arkivmelding opprett.
