### ISSUE TITLE
SaksmappeOppdatering mangler AdministrativEnhet

### ISSUE THREAD

**Issue by Arve-Corneliussen** [ks-no/fiks-arkiv-specification#60]
Det er ikke mulig å omfordele en sak til en annen avdeling.
AdministrativEnhet finnes kun på Saksmappe

**Comment by sturtzel** [comment]
Ja, den må være med. Slikt som er lett å overse før man starter programmeringen.

**Comment by jarleborsheim** [comment]
Fikset og stenger saken
