### ISSUE TITLE
Det er fremdeles inkonsistenser i referanse til mappe

### ISSUE THREAD

**Issue by Arve-Corneliussen** [ks-no/fiks-arkiv-specification#61]
I Registrering ReferanseForelderMappe av type KS.Fiks.Arkiv.Models.V1.Arkivering.Arkivmelding.ReferanseTilMappe.
I MappeOppdatering er ReferanseTilMappe av type KS.Fiks.Arkiv.Models.V1.Metadatakatalog.ReferanseTilMappe

De to ReferanseTilMappe strukturene er forskjellige i arkivmeldingen og metadatakatalogen

**Comment by jarleborsheim** [comment]
Fikset og stenger saken
