### ISSUE TITLE
"Inkluder" attributtet er obligatorisk på søk med responstype nøkler

### ISSUE THREAD

**Issue by Arve-Corneliussen** [ks-no/fiks-arkiv-specification#62]
Men ingen verdier er gyldig for nøkler

**Comment by sturtzel** [comment]
Siden vi har tatt ut mappe etc. fra inkluder bør vi endre denne til minOccurs=0 for alle søk. Hvis man bare vil ha mappen, registreringen, ... er det ikke nødvendig med å angi noen inkluder. Et alternativ er "Ingen" i inkluderlistene, men 0 er best.

**Comment by jarleborsheim** [comment]
Fikset og stenger saken
