### ISSUE TITLE
Uteglemte minOccurs 0 for journalstatus og dokumentstatus?

### ISSUE THREAD

**Issue by sturtzel** [ks-no/fiks-arkiv-specification#75]
Saksstatus har minOccurs 0 og det skulle det antagelig være for de to andre statuskodene også (kun tittel som obligatorisk felt siden den ikke kan konfigureres på en fornuftig måte).

**Comment by jarleborsheim** [comment]
Gjelder dette både i arkivmelding, kvittering og arkivstruktur?

**Comment by sturtzel** [comment]
> Gjelder dette både i arkivmelding, kvittering og arkivstruktur?

Arkivmelding: Ja
Kvittering: Arkivet har alltid denne, så der er minOccurs 1 OK
Arkivstruktur: Dette er resultatet av søk og der er minOccurs 1 OK (også saksstatus har den der).
