### ISSUE TITLE
Kundeønske om forsendelsesstatus

### ISSUE THREAD

**Issue by sturtzel** [ks-no/fiks-arkiv-specification#78]
Forskjellige kanaler gir varierende mulighet for å hente ut status for forsendelsen. Noen, som ordinær brevpost, kan kun gi tilbakemelding som "Sendt", mens man for en rekke digitale kanaler kan følge opp status som "Levert" og "Lest".

I forbindelse med arkivering av eiendomsskattesedler har det kommet opp ønske om å kunne dokumentere denne statusen. GeoIntegrasjon har ikke muligheten og Fiks Arkiv har p.t. ikke muligheten.

Skal feltet inn er det en utfordring med statusverdier. Skal det være et kodefelt? Faste verdier (i tilfelle anbefaling slik det er for en del verdier i Arkivlett)?

Det vil uansett måtte være minOccurs 0 og være et felt i Korrespondansepart.

**Comment by jarleborsheim** [comment]
Vi avventer på mer informasjon om problemet

**Comment by jarleborsheim** [comment]
Vi utvider ikke med dette nå.
