### ISSUE TITLE
Nøkkelord

### ISSUE THREAD

**Issue by sturtzel** [ks-no/fiks-arkiv-specification#79]
Nøkkelord er valgfri funksjonalitet i Noark 5 (kapittel 2.8.2, krav 2.8.3 i Noark 5.5).

Det kan derfor ikke være obligatorisk i Fiks Arkiv.

Enten må vi ta nøkkelord ut  av alle objekter og operasjoner eller dokumentere at nøkkelord inn kan ignoreres i arkivet. Det beste er å ikke ha valgfri funksjonalitet i Fiks Arkiv siden vi da unngår at klienter gjør seg avhengig av funksjonaliteten.

Er det noen fagsystemer som aktivt påfører nøkkelord på det de arkiverer?

**Comment by jarleborsheim** [comment]
Vi lar denne ligge til neste møte

**Comment by jarleborsheim** [comment]
Vi ønsker tilbakemelding på denne fra flere. 
Hvis vi går for dette som valgfritt må det dokumenteres.

**Comment by jarleborsheim** [comment]
Det betyr at vi gjør ikke noen endringer i spesifikasjonen (skjema)
