### ISSUE TITLE
Oppdatering av dokument

### ISSUE THREAD

**Issue by sturtzel** [ks-no/fiks-arkiv-specification#80]
Hvis et dokument feilaktig er satt som ferdig, må dette kunne reverseres.

Vi har tjenesten dokumentbeskrivelseOppdatering som kan benyttes, men det må gås opp / beskrives nærmere om denne skal kunne benyttes til å legge til eller oppdatere et dokumentobjekt.

Skal det være mulig å fjerne eller erstatte et eksisterende dokument?
Skal det være mulig å legge til en ny versjon av et dokument?
Hvordan angi dette? Ved å gjenbruke versjonsnummer og variantformat? Fri bruk av versjonsnummer?

**Comment by JanIvarMoldekleiv** [comment]
Jeg tenker som følger: 
Oppdatering av dokumentobjekt kan potensielt misbrukes  da vi ikke har autentisering pr bruker/system, men prosesserer requester fra alle systemer. 

Jeg mener vi bør innføre en NyVersjonAvDokumentObjekt(DokumentObjektEksternID) -navngivning kan og bør endres ;)
- Oppretter en ny dokumentverjson
- Setter denne aktiv
- Putter filen på den aktuelle dokumentversjonen

Noen utfordringer med overnevnte:

    
    
    Vi mangler her EksternID på Dokumentobjekt. Jeg mener at uten denne så vil en oppdatering være vrien -å referere til versjon og variant er ikke entydig. Alternativet er å referere til arkivets systemid - og da er vi der jeg ikke vil være - altså avhengighet mellom eksternt system og arkivets interne systemider. 
    
Et alternativ til OppdatertDokumentObjekt er jo DokumentbeskrivelseOppdatering som Ragnar foreslår, men da med referanse til EksternID - da kan algoritmen være:
 - Ny verjson av dokumentet opprettes
 - Den nye versjonen settes aktiv. 
    
Uansett - eksternid inn enten på dokumentbeskrivelse eller dokumentobjekt.

**Comment by sturtzel** [comment]
Autentiseringen er en generell utfordring. Vi må forutsette at avsendersystemet har kontroll. Vi har diskutert dette på generell basis. Vi kommer antagelig til å bruke informasjon fra Fiks IO som del av tilgangskontrollen så ikke et byggesakssystem kan få tilgang til f.eks. sosialdata uavhengig av hva som angis som system i arkivmeldingen.

Automatisk ny dokumentversjon kan innføres i arkivet uten at tjenesten endres.

Jeg er litt usikker på om vi trenger eksternnøkkel på dokumentbeskrivelsen da alle operasjoner (hittil) har gått på journalpostnivå. Oppdatering av dokument bryter med dette, men vi kan løse det ved å benytte arkivets ID eller ved å kombinere nøkkel på journalpost med rekkefølgenummer på dokumentbeskrivelsen. Skjønt, bruk av rekkefølgenummer er riski. Og nye attributter forsinker oppstart av test. Foreslår at vi tar diskusjonen i morgen.

**Comment by jarleborsheim** [comment]
Vi bestemte oss for å lage en ny meldingstype for å kunne legge til nytt dokumentobjekt til en dokumentbeskrivelse.
Id inn blir da id til dokumentbeskrivelse. Er det korrekt at det er et systemID felt? Ref oppdatering av dokumentbeskrivelse:

```
    <xs:complexType name="dokumentbeskrivelseOppdatering">
        <xs:sequence>
            <xs:element name="systemID" type="n5mdk:systemID" />
            <xs:element name="tittel" type="n5mdk:tittel" minOccurs="0"/>
            <xs:element name="beskrivelse" type="n5mdk:beskrivelse" minOccurs="0"/>
            <xs:element name="skjerming" type="arkivmelding:skjerming" minOccurs="0"/>
            <xs:element name="gradering" type="arkivmelding:gradering" minOccurs="0"/>
            <xs:element name="dokumentobjekt" type="arkivmelding:dokumentobjekt" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
```

**Comment by sturtzel** [comment]
mappe, registrering, dokumentbeskrivelse og dokumentobjekt har systemID.

**Comment by sturtzel** [comment]
Vi bestemte oss vel for at dokumentobjekt ikke skulle være en del av dokumentbeskrivelseOppdatering, men den ligger på https://github.com/ks-no/fiks-arkiv-specification/issues/89.

Og så ble vel konklusjonen at det skulle være en tjeneste leggTilDokumentobjekt, men ingen oppdater. Tjenesten må angi hvilken dokumentbeskrivelse som skal ha et ekstra dokumentobjekt.

Behov fra Visma EasyCruit til å kunne oppdatere CV / søknad kan løses på en av to måter:
1: Arkivere når søknadsfristen har gått ut
2: Arkivere nye journalposter med tilleggsinfo når søker oppdaterer, EasyCruit kan ellers forholde seg til oppdatert søknad uavhengig av arkiveringen

**Comment by jarleborsheim** [comment]
> Vi bestemte oss vel for at dokumentobjekt ikke skulle være en del av dokumentbeskrivelseOppdatering, men den ligger på #89.
> 
> Og så ble vel konklusjonen at det skulle være en tjeneste leggTilDokumentobjekt, men ingen oppdater. Tjenesten må angi hvilken dokumentbeskrivelse som skal ha et ekstra dokumentobjekt.
> 
> Behov fra Visma EasyCruit til å kunne oppdatere CV / søknad kan løses på en av to måter: 1: Arkivere når søknadsfristen har gått ut 2: Arkivere nye journalposter med tilleggsinfo når søker oppdaterer, EasyCruit kan ellers forholde seg til oppdatert søknad uavhengig av arkiveringen

Det stemmer nok. Jeg har tatt bort det i [denne](https://github.com/ks-no/fiks-arkiv-specification/pull/95) PR'en. Den nye tjenesten har jeg valgt å jobbe med i en egen PR. Kommer snart.
