### ISSUE TITLE
Feltet antallFiler er missvisende?

### ISSUE THREAD

**Issue by jarleborsheim** [ks-no/fiks-arkiv-specification#86]
I arbeidet med dokumentasjon av meldingene ser jeg at i `arkivmelding.xml` kan feltet `antallFiler` være et missvisende navn. Det er ikke antall filer men antall vedlegg. Sender man arkivmelding.xsd uten vedlegg så sender man 1 fil, men skal putte inn 0 da det ikke er noen vedlegg. Burde den hete `antallVedlegg`?

**Comment by sturtzel** [comment]
I arkivsammenheng skiller man mellom hoveddokument og vedlegg. Det er ikke lett å finne et bedre navn og jeg tror ikke de som bruker tjenestene tenker over at selve XML-en er en fil.

**Comment by jarleborsheim** [comment]
Ok. Jeg poengterer i dokumentasjonen da at arkivmelding.xml ikke skal regnes med i antall filer for ordens skyld.
