### ISSUE TITLE
Feil ID-er i arkivmeldingoppdatering

### ISSUE THREAD

**Issue by sturtzel** [ks-no/fiks-arkiv-specification#87]
Underobjekter som korrespondansepart, merknad, kryssreferanse, klassifikasjon etc. har ID som arver fra string i metadatakatalogen.

I arkivmeldingoppdatering er disse gitt navn og type systemID. Det er ingen krav til UID for underobjektene hvilket kan gi valideringsfeil.

**Comment by jarleborsheim** [comment]
I arkivmelding er feltet `kryssreferanseID` ikke tatt med. Men det er med i arkivstruktur. Skulle det vært med som minOccurs="0" i arkivmelding? @sturtzel 

Fra arkivmelding
```
<xs:complexType name="kryssreferanse">
        <xs:sequence>
            <xs:element name="referanseTilKlasse" type="n5mdk:referanseTilKlasse" minOccurs="0"/>
            <xs:element name="referanseTilMappe" type="n5mdk:referanseTilMappe" minOccurs="0"/>
            <xs:element name="referanseTilRegistrering" type="n5mdk:referanseTilRegistrering" minOccurs="0"/>
            <xs:element name="referanseTilDokumentbeskrivelse" type="n5mdk:referanseTilDokumentbeskrivelse"
                        minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
```

**Comment by jarleborsheim** [comment]
Punkt har systemID men jeg klarer ikke se om det er korrekt. Punkt eksisterer ikke i arkivstruktur heller som vel gjør at man egentlig ikke vil få det med når man henter en mappe 🤔 Ergo vil vel man aldri få tilbake en evt id som er opprettet på objektet heller ved hent av mappe. Her tror jeg det er flere hull med andre ord. Hva tror dere?

```
 <xs:complexType name="punktOppdatering">
        <xs:sequence>
            <xs:element name="systemID" type="n5mdk:systemID"/>
            <xs:element name="koordinatsystem" type="n5mdk:koordinatsystem" minOccurs="0"/>
            <xs:element name="x" type="n5mdk:x" minOccurs="0"/>
            <xs:element name="y" type="n5mdk:y" minOccurs="0"/>
            <xs:element name="z" type="n5mdk:z" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
```

**Comment by sturtzel** [comment]
Kryssreferanse: Vi har tatt med systemID på andre objekter med minOccurs=0. Denne vil nok alltid settes av arkivet, men for konsistensens skyld bør vi ta den med.

Punkt: saksmappeOppdatering har punkt, burde hatt punktOppdateringer for konsistens med andre tilsvarende. Og ja, den må inn i arkivstruktur. Ser at også øvrige geografiske objekter mangler (må inn i saksmappe på linje med definisjonen i arkivmelding:
                   <xs:element name="matrikkelnummer" type="matrikkelnummer" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element name="byggident" type="byggident" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element name="planident" type="planident" minOccurs="0"/>
                    <xs:element name="punkt" type="punkt" minOccurs="0"/>
                    <xs:element name="adresse" type="adresse" minOccurs="0" maxOccurs="unbounded"/>

**Comment by jarleborsheim** [comment]
Hvordan er det med oppdatering av disse geografise objektene? Er de nok id i seg selv til at de ikke trenger en id for oppdatering og slett? Altså at oppdatering er unødvendig da man heller sletter og legger til ny? Det ser f.eks. slik ut nå for oppdatering av `byggident`:

```
    <!-- Trengs denne? Eller skal man bare kunne legge til ny og slette? -->
    <xs:complexType name="byggidentOppdatering">
        <xs:sequence>
            <xs:element name="systemID" type="n5mdk:systemID"/>
            <xs:element name="bygningsnummer" type="n5mdk:bygningsnummer" minOccurs="0"/>
            <xs:element name="endringsloepenummer" type="n5mdk:endringsloepenummer" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="byggidentSlett">
        <xs:sequence>
            <xs:element name="systemID" type="n5mdk:systemID"/>
        </xs:sequence>
    </xs:complexType>
```

Kunne det heller sett slik ut (ta bort oppdatering og bare ha ny og slett)?: 

```
    <xs:complexType name="byggidentSlett">
        <xs:sequence>
            <xs:element name="bygningsnummer" type="n5mdk:bygningsnummer" minOccurs="0"/>
            <xs:element name="endringsloepenummer" type="n5mdk:endringsloepenummer" minOccurs="0"/>        </xs:sequence>
    </xs:complexType>
```

**Comment by sturtzel** [comment]
Ikke systemID!

Det er enklere med en form for id for å oppdatere og å slette, men ikke systemID. For bygning og andre der innholdet kun er numre, er det sikkert OK å bruke dette for sletting. Men ved oppdatering må man da slette først siden man ikke får angitt hvilken som skal oppdateres. Jeg tror det er fornuftig med en ID som gjerne kan være et rekkefølgenummer eller kanskje bare bygningsnummeret for denne. Det er opp til server. ID-en må ikke nødvendigvis lagres.

**Comment by jarleborsheim** [comment]
Forstår jeg deg riktig med at du da ønsker en ny id, f.eks. `byggidentID`, som da skal legges til på byggident i arkivstruktur, arkivmelding og være en id på oppdatering og valgfri id på slett?

**Comment by sturtzel** [comment]
Jeg har ingen sterke meninger her. Men uten en form for id er det ikke mulig å tillate oppdatering (der bygningsnummeret kan ha blitt endret). Slett vil måtte bruke bygningsnummeret som ID. Det kunne for så vidt ha blitt benyttet også for oppdatering, men da må det være i form av "opprinnelig bygningsnummer".

**Comment by jarleborsheim** [comment]
Jeg likte ideen om å bare bruke bygningsnummer som identifikator for oppdatering og slett. Da med `opprinnelingBygningsnummer` som id for oppdatering. Se siste commit : https://github.com/ks-no/fiks-arkiv-specification/pull/92/commits/c02ce53fefe4d3ecbab550a4bebf99b92505fa9d

**Comment by jarleborsheim** [comment]
PR er merget inn og tror vi kan avslutte denne saken?

**Comment by jarleborsheim** [comment]
Avslutter denne da den er merget og fikset
