### ISSUE TITLE
Oppdatering av dokumentbeskrivelse, problemstillinger

### ISSUE THREAD

**Issue by sturtzel** [ks-no/fiks-arkiv-specification#89]
arkivmeldingOppdatering har dokumentbeskrivelseOppdatering 0:1. Det ingen "...er" her hvilket vil si at det ikke er mulig å fjerne eksisterende. Det kan være OK.

registreringOppdatering inneholder ikke dokumentbeskrivelseOppdatering. Sammen med ingen "...er" gjør det at det ikke er mulig å legge til nye dokumentregistreringer.

dokumentbeskrivelseOppdatering inneholder dokumentobjekt 0:1. Betyr det at det er mulig å legge til et dokumentobjekt i oppdateringen? Det er referert til hele dokumentobjektet og ikke til en avart dokumentobjektOppdatering. Skal alle felt kunne endres? For hvilken versjon av dokumentet? Det kan være mange dokumentobjekter knyttet til en dokumentbeskrivelse.

https://github.com/ks-no/fiks-arkiv-specification/issues/80 angir mulighet for å legge til nye dokumentobjekt.

Disse inkonsikvensene bør det ryddes i ut fra prinsipper om hva som skal være tillatt av oppdateringer etter at et dokument er arkivert. Og etter at en registrering er arkivert. Skal det være mulig å reversere status må det være mulig å rydde i dokumentene også.

**Comment by jarleborsheim** [comment]
Da kan vi vel stenge denne?
