### ISSUE TITLE
Arkivmelding, klassifikasjonssystem

### ISSUE THREAD

**Issue by sturtzel** [ks-no/fiks-arkiv-specification#90]
klasse har referansen klassifikasjonssystemID.

klassifikasjonssystem har ingen ID i seg. Her er det to alternativer:
1: Legge på feltet klassifikasjonssystemID
2: Fjerne objektet

Jeg anbefaler alternativ 1 for å gi mulighet til å velge fra en liste i et oppsett der man skal angi klasse (klienten kaller da tjeneste for å hente klassifikasjonssystemer).

**Comment by jarleborsheim** [comment]
Skal vi også gjøre noen endringer på oppdatering melding? 
At man skal kunne oppdatere/slette på klasseID og klassifikasjonssystemID og vi tar bort systemID?

Slik ser det ut nå:
```
 <xs:complexType name="klassifikasjonOppdatering">
        <xs:sequence>
            <xs:element name="systemID" type="n5mdk:systemID"/>
            <xs:element name="klasseID" type="n5mdk:klasseID" minOccurs="0"/>
            <xs:element name="tittel" type="n5mdk:tittel" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="klassifikasjonSlett">
        <xs:sequence>
            <xs:element name="systemID" type="n5mdk:systemID"/>
        </xs:sequence>
    </xs:complexType>
```

**Comment by jarleborsheim** [comment]
Løst og stenges
