### ISSUE TITLE
skjermingopphoereraksjon burde ikke være kode direkte

### ISSUE THREAD

**Issue by sturtzel** [ks-no/fiks-arkiv-specification#91]
Alle tilsvarende har en spesifikasjon som arver fra kode. Det bør også denne (i arkivmelding.skjerming).

**Comment by jarleborsheim** [comment]
Tilsvarende som `merknadstype` i metadatakatalog

**Comment by jarleborsheim** [comment]
Stenges da den er løst i PR og merget
